---
title: "Pilot Study"
format: html
author: "Julia Kristensen and Ilia Janfeshan"
---

## Libraries and Reading Data
```{r}
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(dplyr)
library(lmerTest) 

data <- read_csv("pilot.csv")

data$CookingMethod <- factor(data$CookingMethod)
data$DryingMethod  <- factor(data$DryingMethod)
data$Plot <- factor(data$Plot)

data <- data %>%
  group_by(Plot, DryingMethod, CookingMethod) %>%
  summarise(NumQuarters = mean(NumQuarters), .groups = "drop")
```

## Finding Standard Deviation of the SP Factor and the WP Factor
```{r}
fit <- lmer(NumQuarters ~ CookingMethod * DryingMethod +
              (1 | Plot), data)

sp_anova_fit <- anova(fit)
MSE_sp <- sp_anova_fit$`Mean Sq`[3] / sp_anova_fit$`F value`[3]

# One-Way ANOVA on plot totals
plot_tots <- data %>%
  group_by(Plot, DryingMethod) %>%
  summarise(NumQuarters = mean(NumQuarters), .groups = "drop")

wp_ow_anova_fit <- anova(lm(NumQuarters ~ DryingMethod, plot_tots))
MSE_wp <- wp_ow_anova_fit$`Mean Sq`[2]

# c = 1 / number of sub-plots per whole-plot
c <- 0.5

(sd_wp <- sqrt(MSE_wp - (c * MSE_sp)))
(sd_sp <- sqrt(MSE_sp))
```

## Choosing effect sizes
```{r}
data %>%
  group_by(CookingMethod, DryingMethod) %>%
  summarise(NumQuarters = mean(NumQuarters), .groups = "drop")

grand_mean <- mean(data$NumQuarters)
```


```{r}
#| message: false

# Cooking Effect Size: 
mu <- c(2.5,-2.5)

# Drying Effect Size: Because our difference in wait time is large (22 hrs), a difference of only +-10 quarters is considered a significant enough difference.
beta <- c(-10,10)

# Interaction Effect Size:
gamma <- matrix(c(5, -5,
                  -5, 5), nrow = 2, byrow = TRUE)

runs <- 1000

power <- matrix(NA, nrow = 3, ncol = 2)
colnames(power) <- c("CookingMethod", "DryingMethod")
rownames(power) <- c("3", "4", "5")

for (k in 3:5) {
  counterCM <- 0
  counterDM <- 0 
  
  for (r in 1:runs){
    data_sim <- data.frame()
    Plot <- 0
    
    for (n in 1:k){
      
      for (i in 1:2){
        Plot <- Plot + 1
        WP_err <- rnorm(n = 1, mean = 0, sd = sd_wp)
        
        for (j in 1:2){
          Y <- grand_mean + mu[i] + beta[j] + gamma[i,j] + 
            WP_err + rnorm(n = 1, mean = 0, sd = sd_sp)
          
          data_sim <- rbind(data_sim, data.frame(
            Plot = Plot,
            CookingMethod = factor(i),
            DryingMethod = factor(j),
            NumQuarters = Y
          ))
        }
      }
    }
      
      myModel <- lmer(NumQuarters ~ CookingMethod * DryingMethod + 
                        (1 | Plot), data_sim)
      
      anov <- anova(myModel)
      pval <- anov$`Pr(>F)`
      del <- (pval < 0.05)
      
      if (del[1] + del[3] > 0)
        counterCM <- counterCM + 1
      if (del[2] + del[3] > 0)
        counterDM <- counterDM + 1
  }
  power[k-2, 1] <- counterCM / runs
  power[k-2, 2] <- counterDM / runs
}
power
```



